# <span style="color:darkblue"> Lecture 23a - Connecting to SQL via Python </span>

<font size = "5">

In the past lecture:

- We worked directly in SQL
- Carried out basic dataset operations

In  this lecture we will run SQL from Python

- Combine the best of both!
- Learn about escape characters!

# <span style="color:darkblue"> I. Import Libraries and Data </span>

<font size = "5">

<span style="color:red"> Before starting </span> make sure that you have the Python libraries <br>
"psycopg2" and "sqlalchemy" installed in Anaconda

<font size = "5">

Import libraries

In [1]:
# psycogpg2 helps us process SQL commands to send to the server
# sqlalchemy facilitates establishing a connection with the server

import pandas as pd

from sqlalchemy import create_engine
from sqlalchemy.engine import URL
from sqlalchemy import text

<font size = "5">

Import Data

In [2]:
# Import the two car racing datasets

results  = pd.read_csv("data_raw/results.csv")
races    = pd.read_csv("data_raw/races.csv")
circuits = pd.read_csv("data_raw/circuits.csv")

<font size = "5">

Connect to SQL server

- In the default instructions we set <br>
the password to "12345" in windows and <br>
no password for Mac
- ADJUST code accordingly!

In [4]:
# Use the connection details to your server
# These are the default settings.
# "postgresql" is a fixed argument
# If you have a different host,database, username, or password,
# change the corresponding connection details


url_server = URL.create(
    "postgresql",
    host = 'localhost',
    database = 'postgres',
    username = 'postgres',
    port = 5432,
    password  = "8848")

connection = create_engine(url_server)

<font size = "5">

Upload data to SQL

In [5]:
# Import the "results" table, with the name "results_sql"
# Con is an argument to specify the server connection
# "if_exists" is an option to replace the table if it already exists
# You can choose any name instead of "results_sql"

results.to_sql('results',
               con = connection,
               if_exists='replace',
               index=False)

# Import "races"
races.to_sql('races', 
             con = connection, 
             if_exists='replace',
             index=False)

102

<font size = "5">

Try it yourself!

- Upload the "circuits table" into SQL <br>
using ".to_sql()"

In [9]:
# Write your own code

circuits.to_sql('circuits', 
             con = connection, 
             if_exists='replace',
             index=False)

77

# <span style="color:darkblue"> II. "Escape" Characters </span>

<font size = "5">

- Backslash (\\) is known as an escape character
- Used for special operations on strings
- Great for working with text!

<font size = "5">

Multi-line strings (" \ ")

In [7]:
# Use a backslash to define strins over multiple lines
# Do not include a space after "\", otherwise it won't work.
example_string = "This is a string \
defined over multiple lines"

In [8]:
example_string

'This is a string defined over multiple lines'

<font size = "5">

"Double quotes" inside string

In [10]:
#"String "something" "

"String \"something\" "

'String "something" '

In [11]:
# Use a backslash + quotation 

example_double = "This will \"supposedly\" put double quotes inside a string"
print(example_double)

This will "supposedly" put double quotes inside a string

<font size = "5" >
'Single quotes' inside string

In [12]:
# There is no need for a backslash given single quotes 

example_single = "This will 'supposedly' put single quotes inside a string"
print(example_single)

This will 'supposedly' put single quotes inside a string

<font size = "5">

Try it yourself!

- Print a string ``` SELECT "driverId" FROM results; ``` <br> 
using backslash

In [13]:
# Write your own code
print("SELECT \"driverId\" FROM results;")
example_query = "SELECT \"driverId\" FROM results;"
example_query

SELECT "driverId" FROM results;

'SELECT "driverId" FROM results;'

# <span style="color:darkblue"> III. Data operations </span>

<font size = "5">

- In SQL, operations are often called "queries"

<font size = "5">

Import Data from SQL

In [15]:
stored_data = pd.read_sql(text("SELECT * FROM results;"),
            connection)
stored_data

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,16,16,0.0,57,\N,\N,39,12,1:29.833,211.632,11
25836,25842,1096,825,210,20,16,17,17,17,0.0,57,\N,\N,40,20,1:31.158,208.556,11
25837,25843,1096,1,131,44,5,18,18,18,0.0,55,\N,\N,42,11,1:29.788,211.738,9
25838,25844,1096,849,3,6,20,19,19,19,0.0,55,\N,\N,45,14,1:30.309,210.517,130
25839,25845,1096,4,214,14,10,\N,R,20,0.0,27,\N,\N,24,17,1:30.579,209.889,47

In [16]:
# Use "pd.read_sql()"
# - The first argument is string with instructions wrapped in text()
#- The second argument is the server connection

# Extract all data from a column
example1 = pd.read_sql(text("SELECT * FROM results;"), connection)

# Extract a subset of columns
example2 = pd.read_sql(text("SELECT points \
                             FROM results;"), connection)

# Subset based on a string condition
example3 = pd.read_sql(text("SELECT * \
                             FROM races \
                             WHERE name = 'Abu Dhabi Grand Prix';"), connection)


# Note: (i) Remember to include "\"  to be able to define
#           strings over multiple lines
#       (ii) We can include single quotations in the WHERE command
#            without any additional escape characters

example3

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,17,2009,17,24,Abu Dhabi Grand Prix,2009-11-01,11:00:00,http://en.wikipedia.org/wiki/2009_Abu_Dhabi_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,355,2010,19,24,Abu Dhabi Grand Prix,2010-11-14,13:00:00,http://en.wikipedia.org/wiki/2010_Abu_Dhabi_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,858,2011,18,24,Abu Dhabi Grand Prix,2011-11-13,13:00:00,http://en.wikipedia.org/wiki/2011_Abu_Dhabi_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,877,2012,18,24,Abu Dhabi Grand Prix,2012-11-04,13:00:00,http://en.wikipedia.org/wiki/2012_Abu_Dhabi_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,897,2013,17,24,Abu Dhabi Grand Prix,2013-11-03,13:00:00,http://en.wikipedia.org/wiki/2013_Abu_Dhabi_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
5,918,2014,19,24,Abu Dhabi Grand Prix,2014-11-23,13:00:00,http://en.wikipedia.org/wiki/2014_Abu_Dhabi_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
6,945,2015,19,24,Abu Dhabi Grand Prix,2015-11-29,13:00:00,http://en.wikipedia.org/wiki/2015_Abu_Dhabi_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
7,968,2016,21,24,Abu Dhabi Grand Prix,2016-11-27,13:00:00,http://en.wikipedia.org/wiki/2016_Abu_Dhabi_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
8,988,2017,20,24,Abu Dhabi Grand Prix,2017-11-26,13:00:00,http://en.wikipedia.org/wiki/2017_Abu_Dhabi_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
9,1009,2018,21,24,Abu Dhabi Grand Prix,2018-11-25,13:10:00,http://en.wikipedia.org/wiki/2018_Abu_Dhabi_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
10,1030,2019,21,24,Abu Dhabi Grand Prix,2019-12-01,13:10:00,http://en.wikipedia.org/wiki/2019_Abu_Dhabi_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
11,1047,2020,17,24,Abu Dhabi Grand Prix,2020-12-13,13:10:00,http://en.wikipedia.org/wiki/2020_Abu_Dhabi_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
12,1073,2021,22,24,Abu Dhabi Grand Prix,2021-12-12,13:00:00,http://en.wikipedia.org/wiki/2021_Abu_Dhabi_Gr...,2021-12-10,\N,2021-12-10,\N,2021-12-11,\N,2021-12-11,\N,\N,\N
13,1096,2022,22,24,Abu Dhabi Grand Prix,2022-11-20,13:00:00,http://en.wikipedia.org/wiki/2022_Abu_Dhabi_Gr...,2022-11-18,10:00:00,2022-11-18,13:00:00,2022-11-19,11:00:00,2022-11-19,14:00:00,\N,\N
14,1120,2023,23,24,Abu Dhabi Grand Prix,2023-11-26,13:00:00,https://en.wikipedia.org/wiki/2023_Abu_Dhabi_G...,2023-11-24,09:30:00,2023-11-24,13:00:00,2023-11-25,10:30:00,2023-11-25,14:00:00,\N,\N

<font size = "5">

Upper case columns

- In SQL syntax we use double quotes e.g. ``` "driverId" ```
- ```.read_sql()``` requires a string inside a string
- To do so, use escape characters, e.g.   ``` \"driverId\" ```

In [17]:
# Select a column
example4 = pd.read_sql(text('SELECT "driverId" \
                             FROM results;'), connection)

# Compute an aggregate statistic
example5 = pd.read_sql(text("SELECT AVG(points) as mean_points \
                             FROM results \
                             GROUP BY \"driverId\" ;"), connection)

<font size = "5">

Try it yourself!

- Select "raceId" and "constructorId" from results <br>

In [19]:
# Write your own code
example6 = pd.read_sql(text('SELECT \"raceId\", \"constructorId\" \
                             FROM results; '),
                       con = connection)
example6

       raceId  constructorId
0          18              1
1          18              2
2          18              3
3          18              4
4          18              1
...       ...            ...
25835    1096            210
25836    1096            210
25837    1096            131
25838    1096              3
25839    1096            214

[25840 rows x 2 columns]

# <span style="color:darkblue"> IV. Additional Material </span>

<font size = "5">

More about SQL syntax

https://www.w3schools.com/sql/

 <span style="color:red"> How are things stored?: </span> <br>

- Operations like uploading, creating, dropping etc. <br>
are permanent an are available for other server users <br>
who access the data later.
- Commands to view the dataset <br>
(most of what we did today) <br>
are only available during your session <br>
and won't make any lasting changes